name: Deploy to testing org on push to main

on:
    push:
        branches: [main]
        # if something is changed in this path
        paths: 
            - 'force-app/**'

jobs:
    Deploy-code-to-env:
        runs-on: ubuntu-latest
        environment: githubAction

        steps:
            - uses: actions/setup-node@v3

              with:
                node-version: '18'

            - name: 'Checkout source code'

              uses: actions/checkout@v3

              with:
                fetch-depth: '2'

            - name: 'Install SFDX'

              run: npm install @salesforce/cli --global

            - name: 'Install sfdx git delta'

              run: |
                  echo Y | sfdx plugins:install sfdx-git-delta
                  sfdx plugins
            
            - name: 'Create delta packages'

              run: |
                  mkdir changed-sources
                  sf sgd source delta --to "HEAD" --from "HEAD~1" --output changed-sources/ --generate-delta --source force-app/
                  echo "[INFO] Diff generated"

            - name: 'Authenticate to the org'

              run: |
                  echo "${{secrets.SERVER_KEY}}" > server.key
                  sf org login jwt -f server.key -i ${{ secrets.CLIENT_ID }} -o ${{secrets.USERNAME}} -r ${{vars.INSTANCE_URL}} -s

            - name: Detect changed test classes
              id: get-tests
              run: |
                  TEST_CLASSES=$(sf project deploy preview --source-dir changed-sources/force-app --json | \
                  jq -r '.result.files[] | select(.filePath | test(".*Test.cls$")) | .filePath' | \
                  xargs -n 1 basename | sed 's/.cls$//')
    
                  echo "Detected test classes: $TEST_CLASSES"

                  if [ -z "$TEST_CLASSES" ]; then
                    echo "runtests=DummyTest" >> $GITHUB_OUTPUT
                  else
                    echo "runtests=$TEST_CLASSES" >> $GITHUB_OUTPUT
                  fi

            - name: Deploy with only affected test classes
              run: |
                  sf project deploy start \
                  --source-dir changed-sources/force-app \
                  --test-level RunSpecifiedTests \
                  --runtests ${{ steps.get-tests.outputs.runtests }}



            # sf project deploy start --source-dir changed-sources/force-app --test-level RunLocalTests
